### ISSUE TITLE
App abends permanently 

### ISSUE THREAD

**Issue by MK5338** [HarpunDK/Homey.Pushover#2]
Diag data id: d0f4dc7c-faeb-4b73-b85d-8520db560e28
FW: 10.1.0

**Comment by HarpunDK** [comment]
Hi both, thank you for reaching out.

Sorry, just saw the notifications now - my bad.

@MK5338 and @Dabis1705   I'm pretty sure you are missing some configuration.

First: you need to apply your token to the app-settings:

![image](https://github.com/HarpunDK/Homey.Pushover/assets/8235893/2834a3cd-416d-420f-acb9-ebf088a1d6af)


![image](https://github.com/HarpunDK/Homey.Pushover/assets/8235893/9c151095-d91a-40d3-ab97-78e37ab18e6c)


Please restart the app after updating settings.
Let me know if this is not the case and thank you for your reports.

**Comment by MK5338** [comment]
Hi,The app crashes immediately after installation / activation. No chance to apply any settings.Homey pro 2023 runs now on FW 10.1.4. No change.Tried PTP, deleted Pushover app before and reinstalled it after PTP - it still crashes immediately after activation.Am 04.12.2023 um 21:44 schrieb Kim Kokholm ***@***.***>:﻿
Hi both, thank you for reaching out.
Sorry, just saw the notifications now - my bad.
@MK5338 and @Dabis1705   I'm pretty sure you are missing some configuration.
First: you need to apply your token to the app-settings:
image.png (view on web)
image.png (view on web)
Please restart the app after updating settings.
Let me know if this is not the case and thank you for your reports.

**Comment by HarpunDK** [comment]
@MK5338  and @Dabis1705 
Please visit: https://homey.app/a/net.pushover.app/    

New version is in test. Pushed for certification. Better handling of UserToken not configured.
