### ISSUE TITLE
Pushover emergency priority level can't be assigned in homey app pro?

### ISSUE THREAD

**Issue by Michaelj15** [HarpunDK/Homey.Pushover#3]
Pushover emergency priority level can't be assigned in homey app pro?
Like the test on the pushover website, i can assign a emergency priority level to my message. But in the homey pro it isn't possible.

Or is there another solution to repeat the notification ?

**Comment by HarpunDK** [comment]
Hi @Michaelj15 , can you please look at this:
https://community.homey.app/t/app-pro-pushover/95675

Maybe ask the question there. I think I have covered my point of view in the forum, feel free to ask the question again and lets have an conversation.

**Comment by HarpunDK** [comment]
Hi, is this still active?

**Comment by HarpunDK** [comment]
I did release new version.
