### ISSUE TITLE
Can’t fill in rate limit field and settings empty after filling in

### ISSUE THREAD

**Issue by wf-dekker** [HarpunDK/Homey.Pushover#5]
I’m a new user. Trying to fill in the api key, user and device and that works fine but the rate limit field is a box I can click but no keyboard appears (iOS latest version on iPhone)… I can press save and restart the app but settings are not saved if I look in the settings again.

**Comment by HarpunDK** [comment]
Hi @wf-dekker - thank you for your message.

Sorry for not making this clear. The reasoing behind this is a field that the app is maintaining and updating. 
After sending a message using pushover api, a "rate limit" is returned and stored in this value.

Prob. on your plan, you have 10_000 messages available  per month.
For more information: https://pushover.net/api#response   , see "limitations"

**Comment by wf-dekker** [comment]
Hmm ok, so no need to fill it in but it still doesn't work... I can fill in all the possible field and press save but if I then open the settings again all fields are empty again... so can't get it to work... 
and yes I have 10000 available indeed.

**Comment by HarpunDK** [comment]
The default is 10.000. 
Sorry to hear and maybe I can help you. 

Do you get an error popup or something? Do you have the app token and user key? Dont know if Device is "mandatory" as well.

**Comment by wf-dekker** [comment]
No no error. I add api and user key and add my 1 device (but I tried with simple "iPhone" as device name as well)... window just closes, no pop-up nothing. But when I open settings again there is nothing there... 
like it doesn't save.

**Comment by HarpunDK** [comment]
Can you pm me your email? I dont know how to pm in here...

**Comment by HarpunDK** [comment]
Btw, can you please try in a browser - I've only tested in browser.... The javascript behind the settings could behave different on IOS and Web

**Comment by wf-dekker** [comment]
Ah yes, doing it from the developer tools webpage gave me a pop-up after the settings were entered and save pressed and they stated saved. So that is a way to do it... a bit complex but it works now, will test futher. 
If you want me to test it again in a new version let me know!

**Comment by HarpunDK** [comment]
I only use browser from my settings - as well as for other apps. Never tried it from mobile.
